[package]
name = "not_so_chess"
version = "0.1.0"
authors = ["CieciaOne <CieciaV2.0@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
